const reviews = [
	{ name: "Laura W.", review: "The best 12 days of my life, without question.", stars: 5 },
	{ name: "Alex C.", review: "Jemaa el-Fnaa at night is pure theatre.", stars: 5 },
	{ name: "Sofia P.", review: "Fes medina — I was completely lost and loved every minute.", stars: 5 },
	{ name: "Ian B.", review: "The camel ride into the Sahara dunes was surreal.", stars: 5 },
	{ name: "Yuki A.", review: "Our riad in Fes was the most beautiful place I've ever stayed.", stars: 5 },
	{ name: "Marcus L.", review: "Chefchaouen delivered on every single promise.", stars: 5 },
	{ name: "Diane O.", review: "Majorelle Garden was a peaceful escape from the bustle.", stars: 4 },
	{ name: "Nora C.", review: "Lunch at the royal chef's restaurant was unforgettable.", stars: 5 },
	{ name: "Elias M.", review: "Tangier felt like Europe and Africa meeting at the edge.", stars: 4 },
	{ name: "Kim H.", review: "Every city had a completely different energy.", stars: 5 },
	{ name: "Dana F.", review: "Desert camp night was straight out of a fairytale.", stars: 5 },
	{ name: "Omar V.", review: "Hassan II Mosque left me utterly speechless.", stars: 5 },
	{ name: "Petra S.", review: "Oualidia lagoon was quiet, beautiful, and unexpected.", stars: 5 },
	{ name: "Jakub R.", review: "Ait Benhaddou is more impressive than any photo.", stars: 5 },
	{ name: "Priya D.", review: "The tanneries of Fes — the colour and smell stay with you.", stars: 4 },
	{ name: "Leo G.", review: "Saadian Tombs were hauntingly beautiful.", stars: 5 },
	{ name: "Chloe T.", review: "Ifrane was an unexpected and charming surprise.", stars: 5 },
	{ name: "Andrew N.", review: "Everything ran like clockwork the whole twelve days.", stars: 5 },
	{ name: "Ingrid K.", review: "Perfect balance of imperial cities, coast, and desert.", stars: 4 },
	{ name: "Maria S.", review: "The warmth of the Moroccan people made this trip.", stars: 5 },
	{ name: "James F.", review: "Walking through the world's oldest university was humbling.", stars: 5 },
	{ name: "Emma L.", review: "Bahia Palace's tilework and painted ceilings were extraordinary.", stars: 5 },
	{ name: "Sarah W.", review: "The call to prayer echoing over the medina was beautiful.", stars: 5 },
	{ name: "Hugo P.", review: "Loved the sweep from imperial cities to the open desert.", stars: 5 },
	{ name: "Amara J.", review: "The mint tea ritual, everywhere, never once got old.", stars: 4 },
	{ name: "Ben K.", review: "Ouarzazate as a film set felt genuinely surreal.", stars: 4 },
	{ name: "Cleo M.", review: "Sahara camp under the stars — absolutely priceless.", stars: 5 },
	{
		name: "Rachel H.",
		review: "Twelve days felt both too long and not long enough. Marrakech's chaos, the Sahara's quiet, Fes's ancient lanes — each day was a completely different Morocco. The guides throughout were exceptional.",
		stars: 5,
	},
	{
		name: "Luke T.",
		review: "Day 9 in Fes was the highlight — the tannery district, the age of the city, Al Quaraouiyine. Our guide Mohammed brought the history alive in a way no guidebook ever could.",
		stars: 5,
	},
	{
		name: "Sophie A.",
		review: "The shift from Marrakech's energy to Sahara silence on day 6 was something I wasn't prepared for. Sitting by a desert campfire with nothing but stars — Morocco does something to you.",
		stars: 5,
	},
	{
		name: "David C.",
		review: "I've travelled widely but Morocco broke something open in me. The food, the people, the architecture — all so generous. The Moroccan Odyssey gave us just enough time in each place to feel it properly.",
		stars: 5,
	},
	{
		name: "Nadia R.",
		review: "Essaouira on day 2 was a dream. The horseback ride along the beach at sunset — one of those moments you know will stay with you forever. Perfectly timed and beautifully organized.",
		stars: 5,
	},
];

export default reviews;
