const reviews = [
	{ name: "Sarah K.", review: "Sleeping under the Sahara stars changed me.", stars: 5 },
	{ name: "Liam T.", review: "Camel ride to camp at sunset — worth every dirham.", stars: 5 },
	{ name: "Mia R.", review: "The desert silence is unlike anything I've ever known.", stars: 5 },
	{ name: "Omar J.", review: "Dunes at dawn. Nothing prepares you for it.", stars: 5 },
	{ name: "Priya N.", review: "Desert camp was cozy, authentic, and warm.", stars: 5 },
	{ name: "Tom B.", review: "Our guide knew every dune and every story.", stars: 5 },
	{ name: "Jules M.", review: "Best travel decision I've made in years.", stars: 5 },
	{ name: "Ana S.", review: "Camp food cooked over fire was surprisingly good.", stars: 4 },
	{ name: "Elise D.", review: "The Milky Way from the Sahara — I actually cried.", stars: 5 },
	{ name: "Fatima O.", review: "Todra Gorge was a stunning surprise.", stars: 5 },
	{ name: "Rachel H.", review: "Tea with the nomadic family was the highlight.", stars: 5 },
	{ name: "James C.", review: "Ait Benhaddou is more impressive in person.", stars: 5 },
	{ name: "Yuki T.", review: "Perfectly organized from start to finish.", stars: 5 },
	{ name: "Maria G.", review: "Ouarzazate felt like walking into a film.", stars: 5 },
	{ name: "Diane L.", review: "The stars look so different in the desert.", stars: 5 },
	{ name: "Ivan K.", review: "Everything was better than the brochure.", stars: 5 },
	{ name: "Zara M.", review: "Hot by midday but completely worth it.", stars: 4 },
	{ name: "Patrick S.", review: "The Draa Valley date palms are magical.", stars: 5 },
	{ name: "Ben F.", review: "Sandboarding on day 9 — hilarious and brilliant.", stars: 4 },
	{ name: "Chris W.", review: "My daughter and I both had the trip of a lifetime.", stars: 5 },
	{ name: "Nora E.", review: "Second trip with this company. Never disappointed.", stars: 5 },
	{ name: "Henrik P.", review: "The morning dune walk is not to be missed.", stars: 5 },
	{ name: "Carlos V.", review: "Erg Chegaga dunes are wilder and more remote than Merzouga.", stars: 5 },
	{ name: "Leila B.", review: "Friendly, knowledgeable, calm guides throughout.", stars: 5 },
	{ name: "Emma R.", review: "Every single day brought a completely different landscape.", stars: 5 },
	{
		name: "Sophie L.",
		review: "I've done other Sahara tours but this was different. The camp at Erg Chegaga felt genuinely remote — no other tour groups, just the wind and stars. Our guide was extraordinary. Coming back next year.",
		stars: 5,
	},
	{
		name: "Marco A.",
		review: "Todra Gorge on day 11 was a favourite — orange walls rising 300m, a cool stream, and almost no one around. The Berber village lunch that followed was superb. A day I'll never forget.",
		stars: 5,
	},
	{
		name: "Emma W.",
		review: "Sixteen days flew by. Marrakech's chaos gave way to the Draa Valley's calm, then the silence of the Erg Chegaga. The Dades Valley on the return was beautiful. Every guide was professional and warm.",
		stars: 5,
	},
];

export default reviews;
