const tourPlan = [
	{
		day: 1,
		title: "Arrival in Casablanca → Drive to Fes",
		description: "Land in Morocco, stand inside its most iconic mosque, and head for the old imperial capital.",
		activities: [
			"Airport pickup",
			"Visit the Hassan II Mosque",
			"Welcome lunch in Casablanca",
			"Drive to Fes",
			"Overnight in Fes",
		],
	},
	{
		day: 2,
		title: "Fes — Imperial City Experience",
		description: "A full day inside the world's largest living medieval medina.",
		activities: [
			"Guided Fes Old Medina tour",
			"Visit the traditional tanneries",
			"Artisan workshops",
			"Historic old city quarters",
			"Traditional Moroccan dinner",
			"Overnight in Fes",
		],
	},
	{
		day: 3,
		title: "Fes → Ifrane → Merzouga (Sahara Gateway)",
		description: "Cross the Middle Atlas and ride a camel into the great dunes by sunset.",
		activities: [
			"Scenic drive through the Middle Atlas Mountains",
			"Stop in Ifrane",
			"Cedar forest visit",
			"Barbary macaque monkeys",
			"Continue to Merzouga",
			"Camel trek into the Sahara dunes",
			"Sunset over Erg Chebbi",
			"Luxury desert camp",
			"Overnight in the Sahara",
		],
	},
	{
		day: 4,
		title: "Sahara Desert Experience — Horse Riding Day",
		description: "A full day in the dunes on horseback and by 4x4, among the nomad families.",
		activities: [
			"Sunrise over the dunes",
			"Guided horseback riding experience",
			"4x4 desert exploration",
			"Visit nomad families",
			"Optional sandboarding",
			"Second night in the luxury desert camp",
		],
	},
	{
		day: 5,
		title: "Merzouga → Marrakech (Scenic Journey Day)",
		description: "A long, beautiful drive from the dunes to the Red City.",
		activities: [
			"Early departure from the Sahara",
			"Scenic drive through desert landscapes and Atlas foothills",
			"Arrival in Marrakech",
			"Free evening",
			"Overnight in Marrakech",
		],
	},
	{
		day: 6,
		title: "Marrakech — Cultural Experience",
		description: "Palaces, souks, and the greatest square in North Africa.",
		activities: [
			"Visit the Koutoubia Mosque",
			"Visit Bahia Palace",
			"Visit Ben Youssef Madrasa",
			"Guided Medina & Souk tour",
			"Evening at Jemaa el-Fnaa",
			"Overnight in Marrakech",
		],
	},
	{
		day: 7,
		title: "Marrakech — Cultural & Leisure Experience",
		description: "A slower day of gardens, cooking, and a traditional hammam.",
		activities: [
			"Visit the Majorelle Garden",
			"Moroccan cooking class",
			"Traditional Berber family lunch",
			"Hammam & spa experience",
			"Free evening",
			"Overnight in Marrakech",
		],
	},
	{
		day: 8,
		title: "Marrakech → Casablanca → Departure",
		description: "The drive back to the coast, and farewell to Morocco.",
		activities: [
			"Drive to Casablanca",
			"Airport drop off",
			"Departure",
		],
	},
];

export default tourPlan;
