const tourPlan = [
	{
		day: 1,
		title: "Arrival in Casablanca",
		description: "Land in Morocco's largest city and begin at its most iconic landmark on the Atlantic.",
		activities: [
			"Airport pickup and transfer to your hotel",
			"Visit the Hassan II Mosque — one of the largest in the world, rising above the sea",
			"Walk the Casablanca Corniche along the coast",
			"Welcome dinner",
			"Overnight in Casablanca",
		],
	},
	{
		day: 2,
		title: "Casablanca → Marrakech — Imperial Introduction",
		description: "Drive south to the Red City and dive straight into its storied medina.",
		activities: [
			"Scenic drive to Marrakech",
			"Visit the Koutoubia Mosque",
			"Visit Bahia Palace",
			"Visit Ben Youssef Madrasa",
			"Guided Medina & Souk tour",
			"Evening at Jemaa el-Fnaa square",
			"Overnight in Marrakech",
		],
	},
	{
		day: 3,
		title: "Marrakech — Cultural Experience",
		description: "A slower day of gardens, cooking, and a traditional Berber welcome.",
		activities: [
			"Visit the Majorelle Garden",
			"Moroccan cooking class",
			"Traditional Berber family lunch",
			"Hammam & spa experience",
			"Free evening",
			"Overnight in Marrakech",
		],
	},
	{
		day: 4,
		title: "Marrakech → Ait Ben Haddou → Todgha Gorge",
		description: "Cross the High Atlas to a legendary ksar, then continue to a dramatic canyon.",
		activities: [
			"Cross the High Atlas Mountains via the Tizi n'Tichka pass",
			"Visit Ait Ben Haddou — the UNESCO-listed ksar of a hundred films",
			"Continue to the Todgha Gorge",
			"Overnight near Todgha Gorge",
		],
	},
	{
		day: 5,
		title: "Todgha Gorge → Merzouga (Sahara Desert)",
		description: "Reach the great dunes of Erg Chebbi and ride into the sand at sunset.",
		activities: [
			"Morning at the Todgha Gorge",
			"Arrival in Merzouga",
			"Camel trek into the Sahara dunes",
			"Sunset over Erg Chebbi",
			"Luxury desert camp experience",
			"Campfire under the stars",
			"Overnight in the Sahara",
		],
	},
	{
		day: 6,
		title: "Sahara Desert Experience — Horse Riding Day",
		description: "A full day in the dunes on horseback and by 4x4, among the nomad families.",
		activities: [
			"Sunrise over the dunes",
			"Guided horseback riding across the desert",
			"4x4 desert exploration tour",
			"Visit nomad families",
			"Optional sandboarding",
			"Second night in the luxury desert camp",
		],
	},
	{
		day: 7,
		title: "Merzouga → Fes",
		description: "A scenic drive north through the Middle Atlas and its cedar forests.",
		activities: [
			"Scenic drive through the Middle Atlas Mountains",
			"Stop in Ifrane",
			"Cedar forest visit",
			"Barbary macaque monkeys",
			"Arrival in Fes",
			"Free evening",
			"Overnight in Fes",
		],
	},
	{
		day: 8,
		title: "Fes — Imperial City Experience",
		description: "A full day inside the world's largest living medieval medina.",
		activities: [
			"Guided Fes Medina & souks tour",
			"Visit the tanneries",
			"Artisan workshops",
			"Historic quarters",
			"Traditional Moroccan dinner",
			"Overnight in Fes",
		],
	},
	{
		day: 9,
		title: "Fes → Chefchaouen",
		description: "Travel into the Rif Mountains to the town painted entirely in blue.",
		activities: [
			"Travel to Chefchaouen",
			"Guided Blue City walking tour",
			"Free time for photography & shopping",
			"Sunset hike to the Spanish Mosque",
			"Mint tea overlooking the mountains",
			"Overnight in Chefchaouen",
		],
	},
	{
		day: 10,
		title: "Chefchaouen → Tangier — Coastal Finale",
		description: "Descend to the coast where two seas meet, and end the day by the Atlantic.",
		activities: [
			"Visit Cap Spartel",
			"Visit the Hercules Caves",
			"Guided tour of Tangier's Old Medina",
			"Visit the Kasbah & Grand Socco",
			"Seafood dinner by the Atlantic coast",
			"Overnight in Tangier",
		],
	},
	{
		day: 11,
		title: "Tangier — Departure",
		description: "A final Moroccan morning above the Strait of Gibraltar before you fly home.",
		activities: [
			"Mint tea at Café Hafa overlooking the Strait of Gibraltar",
			"Airport transfer and departure",
		],
	},
];

export default tourPlan;
