const reviews = [
	{ name: "Anna T.", review: "Chefchaouen really is that blue. I still can't believe it.", stars: 5 },
	{ name: "Luke S.", review: "Walked for hours through the alleys and never got bored.", stars: 5 },
	{ name: "Nadia F.", review: "The Spanish Mosque view at sunset was breathtaking.", stars: 5 },
	{ name: "Paul D.", review: "Every turn in the medina is a photograph.", stars: 5 },
	{ name: "Mila C.", review: "Tangier surprised me completely.", stars: 5 },
	{ name: "Joel W.", review: "Café Hafa tea above the strait — a perfect moment.", stars: 5 },
	{ name: "Amina B.", review: "Kasbah Museum was rich with history and Andalusian beauty.", stars: 4 },
	{ name: "Tom G.", review: "Ras el Ma spring after all that walking — so refreshing.", stars: 5 },
	{ name: "Sara K.", review: "The locals in Chefchaouen were so warm and kind.", stars: 5 },
	{ name: "Raj P.", review: "Loved the cool mountain air after the coastal heat.", stars: 4 },
	{ name: "Elodie M.", review: "Cap Spartel — where two oceans meet. Incredible.", stars: 5 },
	{ name: "Chris N.", review: "Small group made it feel personal and unhurried.", stars: 5 },
	{ name: "Leila H.", review: "Medina shopping was colourful, lively, and fun.", stars: 4 },
	{ name: "Matt R.", review: "Hercules Cave was unexpected and fascinating.", stars: 4 },
	{ name: "Caro V.", review: "Great pace — not rushed, never bored.", stars: 5 },
	{ name: "Hiroshi K.", review: "Perfect tour for photographers. Every wall is art.", stars: 5 },
	{ name: "Ingrid S.", review: "The blue paint is even more vivid in person.", stars: 5 },
	{ name: "Aisha O.", review: "Our guide knew the history behind every corner.", stars: 5 },
	{ name: "David L.", review: "Tetouan medina was a wonderful hidden gem.", stars: 4 },
	{ name: "Florence T.", review: "Akchour gorge hike was one of the best days of the trip.", stars: 5 },
	{ name: "Victor A.", review: "Smoothest travel experience I've had in Africa.", stars: 5 },
	{ name: "Grace K.", review: "Volubilis ruins were a wonderful bonus on day 10.", stars: 5 },
	{ name: "Hugo M.", review: "Asilah was charming — really glad we stopped there.", stars: 5 },
	{
		name: "Helen K.",
		review: "Chefchaouen surpassed every expectation. Standing in an alley at sunrise with the blue catching early light — it felt like a dream. The guide showed us spots no tourist map would ever find.",
		stars: 5,
	},
	{
		name: "Phil M.",
		review: "Tangier was the real surprise of the trip. I expected just a transit stop but ended up not wanting to leave. Two full days, great food, and Café Hafa's mint tea with the sea below was unforgettable.",
		stars: 5,
	},
	{
		name: "Yasmine B.",
		review: "The drive from Tangier through the Rif Mountains to Chefchaouen was as beautiful as the destination. Our driver stopped at a viewpoint that left us speechless. Outstanding attention to detail throughout.",
		stars: 5,
	},
];

export default reviews;
